/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import business.VihecleInformationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class DriverViewJPanel extends javax.swing.JPanel {

    private JPanel ProcessContainer;
    private VihecleInformationDirectory vihecleinformationdirectory;
    /**
     * Creates new form DriverViewJPanel
     */


    DriverViewJPanel(JPanel ProcessContainer, VihecleInformationDirectory vihecleinformationdirectory) {
        initComponents();
        this.ProcessContainer = ProcessContainer;
        this.vihecleinformationdirectory = vihecleinformationdirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanagevihecle = new javax.swing.JButton();
        btnnewdriver = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        btnmanagevihecle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnmanagevihecle.setText("Manage your vihecle");
        btnmanagevihecle.setToolTipText("");
        btnmanagevihecle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagevihecleActionPerformed(evt);
            }
        });

        btnnewdriver.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnnewdriver.setText("Become a new driver");
        btnnewdriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewdriverActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnnewdriver, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnmanagevihecle, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnewdriver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmanagevihecle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagevihecleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagevihecleActionPerformed
        // TODO add your handling code here:
        ManagedriverJPanel panel = new ManagedriverJPanel(ProcessContainer, vihecleinformationdirectory);
        ProcessContainer.add("NanagedriverJPanel", panel);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.next(ProcessContainer);

    }//GEN-LAST:event_btnmanagevihecleActionPerformed

    private void btnnewdriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewdriverActionPerformed
        // TODO add your handling code here:
        CreateJPanel panel = new CreateJPanel(ProcessContainer, vihecleinformationdirectory);
        ProcessContainer.add("CreateJPanel", panel);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.next(ProcessContainer);
    }//GEN-LAST:event_btnnewdriverActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        ProcessContainer.remove(this);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.previous(ProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnmanagevihecle;
    private javax.swing.JButton btnnewdriver;
    // End of variables declaration//GEN-END:variables
}
