/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import business.VihecleInformation;
import business.VihecleInformationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class ManagedriverJPanel extends javax.swing.JPanel {

    private JPanel ProcessContainer;
    private VihecleInformationDirectory vihecleinformationdirectory;
    /**
     * Creates new form ManagedriverJPanel
     */


    ManagedriverJPanel(JPanel ProcessContainer, VihecleInformationDirectory vihecleinformationdirectory) {
        initComponents();
        this.ProcessContainer = ProcessContainer;
        this.vihecleinformationdirectory = vihecleinformationdirectory;
        populatetable();
    }
    
    private void populatetable(){
        DefaultTableModel dtm = (DefaultTableModel) tbldriver.getModel();
        dtm.setRowCount(0);
        for (VihecleInformation vihecle : vihecleinformationdirectory.getViheclelist()){
            Object[] row = new Object[2];
            row[0]=vihecle;
            row[1]= vihecle.getModulenum();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldriver = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearchnumber = new javax.swing.JButton();
        btnviewdetail = new javax.swing.JButton();
        txtsearchdriver = new javax.swing.JTextField();
        btnsearch1 = new javax.swing.JButton();
        txtsearchnumber = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Module Number", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        setBackground(new java.awt.Color(0, 0, 0));

        tbldriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Module Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldriver);

        btnback.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnsearchnumber.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsearchnumber.setText("search by your Name");
        btnsearchnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchnumberActionPerformed(evt);
            }
        });

        btnviewdetail.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnviewdetail.setText("view details");
        btnviewdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdetailActionPerformed(evt);
            }
        });

        btnsearch1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnsearch1.setText("search by your Number");
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnviewdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsearchnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsearchdriver, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsearchnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearchnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearchdriver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearchnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnviewdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        ProcessContainer.remove(this);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.previous(ProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = tbldriver.getSelectedRow();
        if (selectedrow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "would you like to delete your information?", "warning", dialogButton);
            if (dialogResult ==JOptionPane.YES_OPTION);{
            VihecleInformation vihecle = (VihecleInformation) tbldriver.getValueAt(selectedrow, 0);
            vihecleinformationdirectory.deletevihecle(vihecle);
            populatetable();
        }
        }
        else
            JOptionPane.showMessageDialog(null, "Please select any account", "warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchnumberActionPerformed
        // TODO add your handling code here:
        VihecleInformation result = vihecleinformationdirectory.searchvihecle(txtsearchdriver.getText());
        if(result == null){
            JOptionPane.showMessageDialog(null, "Please type your name on the box", "warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        driverdetailJPanel panel = new driverdetailJPanel(ProcessContainer, result);
        ProcessContainer.add("driverdetailJPanel", panel);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.next(ProcessContainer);
        }
    }//GEN-LAST:event_btnsearchnumberActionPerformed

    private void btnviewdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdetailActionPerformed
        // TODO add your handling code here:
        int selectedrow = tbldriver.getSelectedRow();
        if (selectedrow < 0){
            JOptionPane.showMessageDialog(null, "Please select any account!", "warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            VihecleInformation vihecle = (VihecleInformation) tbldriver.getValueAt(selectedrow, 0);
            driverdetailJPanel panel = new driverdetailJPanel(ProcessContainer, vihecle);
            ProcessContainer.add("driverdetailJPanel", panel);
            CardLayout layout = (CardLayout) ProcessContainer.getLayout();
            layout.next(ProcessContainer);
            
        }
    }//GEN-LAST:event_btnviewdetailActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        // TODO add your handling code here:
        VihecleInformation result2 = vihecleinformationdirectory.searchmodulenumber(txtsearchnumber.getText());
        if (result2 == null){
            JOptionPane.showMessageDialog(null, "Please type your module number on the box", "warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
        driverdetailJPanel panel = new driverdetailJPanel(ProcessContainer, result2);
        ProcessContainer.add("driverdetailJPanel", panel);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.next(ProcessContainer);
        }
    }//GEN-LAST:event_btnsearch1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JButton btnsearchnumber;
    private javax.swing.JButton btnviewdetail;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbldriver;
    private javax.swing.JTextField txtsearchdriver;
    private javax.swing.JTextField txtsearchnumber;
    // End of variables declaration//GEN-END:variables
}
