/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import business.VihecleInformationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class WorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel ProcessContainer;
    private VihecleInformationDirectory vihecleinformationdirectory;

    /**
     * Creates new form ProcessContainer
     */


    WorkAreaJPanel(JPanel ProcessContainer, VihecleInformationDirectory vihecleinformationdirectory) {
        initComponents();
        this.ProcessContainer = ProcessContainer;
        this.vihecleinformationdirectory = vihecleinformationdirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndriver = new javax.swing.JButton();
        btnpassenger = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        btndriver.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btndriver.setText("You are a driver");
        btndriver.setToolTipText("");
        btndriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndriverActionPerformed(evt);
            }
        });

        btnpassenger.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnpassenger.setText("You are a passenger");
        btnpassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpassengerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnpassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btndriver, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndriver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndriverActionPerformed
        // TODO add your handling code here:
        DriverViewJPanel driverJPanel = new DriverViewJPanel(ProcessContainer, vihecleinformationdirectory);
        ProcessContainer.add("DriverViewJPanel", driverJPanel);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.next(ProcessContainer);
        
    }//GEN-LAST:event_btndriverActionPerformed

    private void btnpassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpassengerActionPerformed
        // TODO add your handling code here:
        passengerviewJPanel panel = new passengerviewJPanel(ProcessContainer, vihecleinformationdirectory);
        ProcessContainer.add("passengerviewJPanel", panel);
        CardLayout layout = (CardLayout) ProcessContainer.getLayout();
        layout.next(ProcessContainer);
    }//GEN-LAST:event_btnpassengerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndriver;
    private javax.swing.JButton btnpassenger;
    // End of variables declaration//GEN-END:variables
}
